import "./globals.css";
import {Source_Sans_3} from "next/font/google";
import {AOSInit} from "@/aos";

const font = Source_Sans_3({subsets: ["latin"]});

export const metadata = {
	title: "Deepansh Chopra",
	description: "Generated by create next app",
};

export default function RootLayout({children}) {
	return (
		<html lang="en">
			<AOSInit />
			<body>
				<main className={`${font.className} max-w-[1440px] mx-auto`}>
					{children}
				</main>
			</body>
		</html>
	);
}
